App\User\Model\User\Embedded\UserFullName:
    type: embeddable
    fields:
        name:
            column: first_name
            type: string
        surname:
            column: last_name
            type: string
        patronymic:
            column: patronymic
            type: string
            nullable: true
