parameters:
    locale: '%env(LOCALE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Base\:
        resource: '../src/Base/*'
        exclude: '../src/Base/{DependencyInjection,Entity,Migration,Kernel.php}'

    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migration,Kernel.php}'

    App\User\Controller\:
        resource: '../src/App/User/Controller'
        tags: ['controller.service_arguments']

    App\Patient\Controller\:
        resource: '../src/App/Patient/Controller'
        tags: ['controller.service_arguments']

    base.serializer.normalizer.entity:
        class: 'Base\Utils\Serializer\Symfony\Normalizer\EntityNormalizer'
        public: false
        autowire: true
        autoconfigure: true
        tags:
            - { name: serializer.normalizer }

    App\User\Utils\PasswordEncoder\Symfony\PasswordEncoder:
        class: App\User\Utils\PasswordEncoder\Symfony\PasswordEncoder
        arguments:
            - '%env(SALT)%'

    App\User\DataFixtures\UserFixture:
        class: App\User\DataFixtures\UserFixture
        arguments:
            - '@App\User\Action\User\Create\CreateUserAction'

    App\Patient\DataFixtures\PatientFixture:
        class: App\Patient\DataFixtures\PatientFixture
        arguments:
            - '@App\Patient\Action\Patient\Create\CreatePatientAction'

    App\Region\DataFixtures\RegionFixture:
        class: App\Region\DataFixtures\RegionFixture
        arguments:
            - '@App\Region\Action\Region\Create\CreateRegionAction'

    Base\Command\FillDevDatabaseCommand:
        class: Base\Command\FillDevDatabaseCommand
        arguments:
            - '%env(APP_ENV)%'

    Base\Command\CreateAdminUserCommand:
        class: Base\Command\CreateAdminUserCommand
        arguments:
            - '%env(ADMIN_USERNAME)%'
            - '%env(ADMIN_EMAIL)%'
            - '%env(ADMIN_PASSWORD)%'
            - '%env(ADMIN_SURNAME)%'
            - '%env(ADMIN_NAME)%'
            - '%env(ADMIN_PATRONYMIC)%'
            - '@App\User\Action\User\Create\CreateUserAction'
